# P4 single-node / single-replica broker.  It is intentionally not HA.
brokerClusterName=DefaultCluster
brokerName=bdlh-broker
brokerId=0
listenPort=10911
brokerIP1=rmq-broker
autoCreateTopicEnable=false
autoCreateSubscriptionGroup=false
storePathRootDir=/home/rocketmq/store
storePathCommitLog=/home/rocketmq/store/commitlog
deleteWhen=04
fileReservedTime=72
flushDiskType=ASYNC_FLUSH
